import { Command } from 'commander';
import { writeFileSync, existsSync, statSync } from 'node:fs';
import { globSync } from 'glob';
import { parsePhpFile } from './parser/parse-file.js';
import { emitInterfaces, emitEnumTypes, emitClassInterfaces, emitClassMap } from './generator/emit-ts-interfaces.js';
import { emitProxyConfigs } from './generator/emit-proxy-configs.js';
import type { ServiceContract, EnumDecl, ClassDecl } from './types.js';

export interface CliOptions {
    input: string[];
    output: string;
    watch: boolean;
    banner: boolean;
}

/**
 * Find all PHP files from input paths (files or glob patterns).
 */
function resolveInputFiles(inputs: string[]): string[] {
    const files: string[] = [];

    for (const input of inputs) {
        // If it's a directory, scan for *.php
        if (existsSync(input) && statSync(input).isDirectory()) {
            const found = globSync(`${input}/**/*.php`);
            files.push(...found);
        } else {
            // Treat as glob pattern
            const found = globSync(input);
            files.push(...found);
        }
    }

    // Deduplicate
    return [...new Set(files)].sort();
}

/**
 * Run the code generator.
 */
export function runCodegen(options: CliOptions): void {
    const files = resolveInputFiles(options.input);

    if (files.length === 0) {
        console.error('No PHP files found matching the input pattern.');
        process.exit(1);
    }

    const allContracts: ServiceContract[] = [];
    const allEnums: EnumDecl[] = [];
    const allClasses: ClassDecl[] = [];

    for (const file of files) {
        const result = parsePhpFile(file);
        allContracts.push(...result.contracts);
        allEnums.push(...result.enums);
        allClasses.push(...result.classes);
    }

    const enumNames = new Set(allEnums.map((e) => e.name));
    const classNames = new Set(allClasses.map((c) => c.name));
    const typeNames = new Set([...enumNames, ...classNames]);

    if (allContracts.length === 0 && allEnums.length === 0 && allClasses.length === 0) {
        console.log('No RPC contract interfaces, enums, or classes found.');
        return;
    }

    if (allContracts.length > 0) {
        console.log(`Found ${allContracts.length} contract(s) in ${files.length} file(s):`);
        for (const c of allContracts) {
            console.log(`  ${c.fqcn} (${c.methods.length} methods)`);
        }
    }
    if (allEnums.length > 0) {
        console.log(`Found ${allEnums.length} enum(s):`);
        for (const e of allEnums) {
            const backing = e.backingType ? `: ${e.backingType}` : '';
            console.log(`  ${e.fqcn}${backing} (${e.cases.length} cases)`);
        }
    }
    if (allClasses.length > 0) {
        console.log(`Found ${allClasses.length} DTO class(es):`);
        for (const c of allClasses) {
            console.log(`  ${c.fqcn} (${c.properties.length} properties)`);
        }
    }

    // Generate output
    const parts: string[] = [];

    if (options.banner) {
        parts.push('// ═══════════════════════════════════════════════════════');
        parts.push('// Auto-generated by @php-websocket-rpc/codegen.');
        parts.push('// Do not edit this file directly.');
        parts.push('// ═══════════════════════════════════════════════════════');
        parts.push('');
        parts.push("import type { ProxyOptions } from '@php-websocket-rpc/client';");
        parts.push('');
    }

    // Class interfaces first, then classMap, then enums, then contract interfaces, then configs
    // (so each section can reference types from earlier sections)
    parts.push(emitClassInterfaces(allClasses, typeNames));
    parts.push(emitClassMap(allClasses));
    parts.push(emitEnumTypes(allEnums));
    parts.push(emitInterfaces(allContracts, typeNames));
    parts.push('');
    parts.push(emitProxyConfigs(allContracts));

    const output = parts.join('\n').replace(/\n{3,}/g, '\n\n') + '\n';

    writeFileSync(options.output, output, 'utf-8');
    console.log(`\nGenerated: ${options.output}`);
}

export function main(): void {
    const program = new Command();

    program
        .name('php-rpc-codegen')
        .description('Generate TypeScript interfaces and proxy configs from PHP RPC contracts')
        .version('0.1.0')
        .requiredOption('-i, --input <paths...>', 'Input PHP file(s) or directory/glob patterns')
        .requiredOption('-o, --output <path>', 'Output TypeScript file')
        .option('-w, --watch', 'Watch mode — re-generate on file changes')
        .option('--no-banner', 'Omit the auto-generated header comment')
        .parse(process.argv);

    const opts = program.opts() as CliOptions;

    runCodegen(opts);
}

// Auto-run when executed directly
main();
